# Generated by Django 4.1.1 on 2023-01-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
