# Generated by Django 4.1.1 on 2023-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0003_alter_questions_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
