# Generated by Django 4.1.1 on 2023-01-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0004_alter_questions_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
